/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.bpodolski.caspergis.system.action.wizard;

import javax.swing.JPanel;

public final class NewProjectVisualPanel2 extends JPanel {

    /**
     * Creates new form NewProjectVisualPanel2
     */
    public NewProjectVisualPanel2() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Base Parametrs";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCRS = new javax.swing.JButton();
        edtCRS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(btnCRS, org.openide.util.NbBundle.getMessage(NewProjectVisualPanel2.class, "NewProjectVisualPanel2.btnCRS.text")); // NOI18N
        btnCRS.setToolTipText(org.openide.util.NbBundle.getMessage(NewProjectVisualPanel2.class, "NewProjectVisualPanel2.btnCRS.toolTipText")); // NOI18N
        btnCRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRSActionPerformed(evt);
            }
        });

        edtCRS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        edtCRS.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        edtCRS.setText(org.openide.util.NbBundle.getMessage(NewProjectVisualPanel2.class, "NewProjectVisualPanel2.edtCRS.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NewProjectVisualPanel2.class, "NewProjectVisualPanel2.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(edtCRS, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCRS))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtCRS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCRS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRSActionPerformed


    }//GEN-LAST:event_btnCRSActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCRS;
    private javax.swing.JTextField edtCRS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
